### ISSUE TITLE
Change Thumbnail Width

### ISSUE THREAD

**Issue by muradsofiyev** [rap2hpoutre/vue-picture-swipe#4]
How to change thumbnail width?

**Comment by rap2hpoutre** [comment]
It's not implemented yet, but you can just add a style in your css file:

```css
img[itemprop="thumbnail"] {
    width: 500px;
}
```

Or via JS:

```javascript
document.querySelector('img[itemprop="thumbnail"]').style.width = '500px';
```

Let me know if it solved your issue.

PS: sorry for late answer.
